### ISSUE TITLE
ClearVision - Sapphire - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by SandroTheExiled** [Zerthox/ClearVision#101]
When i activate your Theme i cant click the left side (Server/Main Page) anymore

Edit : 
never mind it was a plugin where i fucked up the css part sry

**Comment by Zerthox** [comment]
Please note that Discord Source is an unofficial source of BetterDiscord themes/plugins, which basically means you're using some of the themes/plugin you'll find there at your own risk.
