### ISSUE TITLE
Seems broken with latest update

### ISSUE THREAD

**Issue by trollollol123** [Zerthox/ClearVision#102]
Seems broken with latest update

**Comment by iiPotatoFlamesii** [comment]
Happened to me aswell, all of the themes from clearvision aren't showing the background, but everything else works fine.

**Comment by piks** [comment]
yea discord updated a lot of their stylings last update, I'm effected as well

**Comment by untuned** [comment]
There is a temporary fix in the Discord server, located at the top of the pinned messages in #support.
https://clearvision.gitlab.io/join

**Comment by Grip555** [comment]
Invite expired for me.

**Comment by untuned** [comment]
@Grip555 https://discord.gg/dHaSxn3

**Comment by Grip555** [comment]
I still have issues joining it. Is it full or does it require an invite?

**Comment by Grip555** [comment]
Why is it closed I still have the issue!

**Comment by untuned** [comment]
> Why is it closed I still have the issue!

You may be banned.  Add me on Discord: untuned#0001

**Comment by untuned** [comment]
Fixes for V6, not my code, combined code from several ppl here, sorry I didn't really keep track of your names - make sure to be on dark theme on discord
Put it in the Custom CSS thing save and update (bottom of settings)
```
/* Main theme fix */
.theme-dark {
    background: transparent;
    --deprecated-panel-background: rgba(0,0,0,0.4);
    --channels-default: var(--main-color);
    --background-secondary: rgba(0,0,0,0.2);
    --text-link: var(--main-color);
    
}

 
/* Makes online role display white instead of blue */
.roleColor-36x_Mz {
    color: #fff;
}

/* Home button */
.childWrapper-anI2G9 {
    background: rgba(0,0,0,.3) var(--home-icon) var(--home-position)/var(--home-size);
}

.wrapper-1BJsBx.selected-bZ3Lue .childWrapper-anI2G9, .wrapper-1BJsBx:hover .childWrapper-anI2G9 {
    background-color: var(--main-color);
}
```

-----------------------------------------

Fixes for V5 (also not mine, just trying to get everything in one post lol. I have no idea if the extra stuff from the V6 is needed for V5 or breaks stuff, but people reported this working so that's what I'm sharing)
Put it in the Custom CSS thing save and update (bottom of settings)
```
.theme-dark {
    background: transparent;
    --deprecated-panel-background: rgba(0,0,0,0.4);
    --channels-default: var(--main-color);
    --background-secondary: rgba(0,0,0,0.2);
    --text-link: var(--main-color);
} 
/* Makes online role display white instead of blue */
.roleColor-36x_Mz {
    color: #fff;
}
```

**Comment by Grip555** [comment]
> 
> 
> > Why is it closed I still have the issue!
> 
> You may be banned. Add me on Discord: untuned#0001

I don't know why I would be I've never been on that server before. :/

**Comment by Vitoire** [comment]
Is that a temporary fix? Because while it fixed general issues with the theme in itself, it isn't transparent anymore :/ Thanks for the update, though.

**Comment by untuned** [comment]
> Is that a temporary fix? Because while it fixed general issues with the theme in itself, it isn't transparent anymore :/ Thanks for the update, though.

An update has been posted for CV, see if that helps.

**Comment by Vitoire** [comment]
> 
> 
> > Is that a temporary fix? Because while it fixed general issues with the theme in itself, it isn't transparent anymore :/ Thanks for the update, though.
> 
> An update has been posted for CV, see if that helps.

Downloaded the new CV v6 and it seems to work great. One question I have is, however, if it's possible to make the theme background completely transparent? I had v5 and before Discord decided to break themes with the new update, I managed to make my theme completely transparent. Is that possible for v6 as well?

**Comment by Zerthox** [comment]
Has been fixed by now.

@Vitoire if you still need help with getting window transparency to work with the theme, please ask in the [ClearVision server](https://clearvision.gitlab.io/join) or [create another issue](https://github.com/Zerthox/ClearVision/issues/new).
