### ISSUE TITLE
ClearVision - Sapphire - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by TheViper4Life** [Zerthox/ClearVision#103]
Discord recently updated their layout, which seems to have broken the transparency of this theme, as well the other colors that are just like it.  These are great themes, but you kind of lose something now. Just wanted to make someone aware.

**Comment by Zerthox** [comment]
Closed in favor of #102.

Please note that Discord Source is an unofficial source of BetterDiscord themes/plugins, which basically means you're using some of the themes/plugin you'll find there at your own risk.
