### ISSUE TITLE
ClearVision - Amethyst - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by rjkdgeek** [Zerthox/ClearVision#105]
Love the theme. However, new discord client update broke images showing on the main window. It only shows the image on the top border. This error has happened with many themes throughout the better discord library.
![GitHub feedback](https://user-images.githubusercontent.com/53441281/64587358-02d8ff80-d354-11e9-8bfc-7ba09cd81980.png)

**Comment by Clamier** [comment]
yea i have same problem with all colors.
until fixed i find one theme wich work Bubble_Time by DevilsLynAvenged

**Comment by Zerthox** [comment]
Closed in favor of #102.

Please note that Discord Source is an unofficial source of BetterDiscord themes/plugins, which basically means you're using some of the themes/plugin you'll find there at your own risk.
