### ISSUE TITLE
ClearVision - Sapphire - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by Inscriptox** [Zerthox/ClearVision#107]
discord update broke the background (everything but the very top is just black). methods to fix it that i googled did not work, so seems to just have to be waiting for a fix from the maker

**Comment by Zerthox** [comment]
Closed in favor of #102.

Please note that Discord Source is an unofficial source of BetterDiscord themes/plugins, which basically means you're using some of the themes/plugin you'll find there at your own risk.

**Comment by Inscriptox** [comment]
That has literally nothing to do with the fact a discord update broke the
theme and the creator of it needs to fix it.
