### ISSUE TITLE
ClearVision - Sapphire - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by Inscriptox** [Zerthox/ClearVision#111]
When will an update to fix the issue in the picture be posted? Only thing visible for the theme is the top, everything else is entirely black and missing. It's the same thing for all of the Clearvision themes.
![image](https://user-images.githubusercontent.com/55151528/64761898-298d6680-d50b-11e9-999d-47bdb0f4efe1.png)

**Comment by untuned** [comment]
https://github.com/Zerthox/ClearVision/issues/102

**Comment by Grip555** [comment]
I also have this issue and for some reason only the Discord server which I can't access has the solution. :/
