### ISSUE TITLE
ClearVision v6- Beta - Discord Source

### ISSUE THREAD

**Issue by Swegii** [Zerthox/ClearVision#114]
idk whats going https://media.discordapp.net/attachments/624734288381739011/624734589679697930/Snapchat-1137464396.jpg?width=377&height=671
And theme was broken
https://media.discordapp.net/attachments/552232790712909840/624738239638536192/unknown.png?width=1191&height=670
halp plox m8s ;<

**Comment by Swegii** [comment]
Sorry my english is bad ;/

**Comment by Vitoire** [comment]
https://github.com/Zerthox/ClearVision/issues/102

Yes, Discord is in the process of doing some update shenanigans and it seems themes might break more often than not. The same happened to my theme as well. 

But please try to stick to one thread, it helps keep everything in one place.
