### ISSUE TITLE
Can you fix it?

### ISSUE THREAD

**Issue by Kuju29** [Zerthox/ClearVision#115]
Themes : ClearVision_Ruby v5 by Zerthox
![image](https://user-images.githubusercontent.com/22098092/73590392-6edf1e80-4514-11ea-9fee-445a475c8342.png)

**Comment by Kuju29** [comment]
and
![image](https://user-images.githubusercontent.com/22098092/73590408-93d39180-4514-11ea-8432-2f3d71087b2a.png)

**Comment by JustKillu** [comment]
same

**Comment by Zeadar** [comment]
Dunno about the friends and activity areas but I got rid of the grey message box by adding `.da-channelTextArea{
    background-color : RGBA(0, 0, 0, .4) !important;
}

.theme-dark{
    --channeltextarea-background : RGBA(0, 0, 0, 0) !important;
}` to custom css

**Comment by Zeadar** [comment]
Dunno about the friends and activity areas but I got rid of the grey message box by adding 

```
.da-channelTextArea{
    background-color : RGBA(0, 0, 0, .4) !important;
}

.theme-dark{
    --channeltextarea-background : RGBA(0, 0, 0, 0) !important;
} 
```

to custom css
