### ISSUE TITLE
Desktop app

### ISSUE THREAD

**Issue by Lleneallyn** [Zerthox/ClearVision#12]
Hallo, 
I wanna ask, how to get font size bigger?
https://s12.postimg.org/bcz3phbnx/Screenshot_09_03.png
Thx

**Comment by Zerthox** [comment]
If you dont want it to look a bit weird, you'd have to adjust all of the font-size properties.

**Comment by Zerthox** [comment]
I'm just gonna close this, cause it's not something concerning the theme, but rather a general question about Discord's CSS.
