### ISSUE TITLE
Notification Settings background completely white

### ISSUE THREAD

**Issue by RagdollClash** [Zerthox/ClearVision#27]
I've made sure to disable any plugins and other themes that happened to be enabled during the time. Using latest BetterDiscord version with latest Discord Canary. Screenshot is using ClearVision Amethyst but the other variants of the theme are affected as well.
![image](https://cloud.githubusercontent.com/assets/15317421/25775688/c8bfce92-325f-11e7-8364-a165edac1f13.png)

**Comment by Zerthox** [comment]
Fixed
