### ISSUE TITLE
Settings for personal and server are not themed

### ISSUE THREAD

**Issue by DetermineAbsurd** [Zerthox/ClearVision#28]
The personal settings and server settings have a gray background and do not go with the theme. Running latest BetterDiscord.
![discord_2017-05-07_00-04-50](https://cloud.githubusercontent.com/assets/12719642/25777853/25fc5d2e-32b9-11e7-9c30-1515e733aa50.png)

**Comment by OmgDani** [comment]
Zerthox is working on this, give him some time.

**Comment by Zerthox** [comment]
Fixed
