### ISSUE TITLE
Certain Popout Objects may be difficult to read

### ISSUE THREAD

**Issue by Spartan322** [Zerthox/ClearVision#3]
certain popout tags that use the class `themed-popout` color alpha seems to occasionally allow the internal objects (most notably the white colored text) to be hard to read. I've found it most notable on the Amber version, but testing on Amethyst and Emerald versions also appear to suffer.

References: http://imgur.com/a/tUhMp (as you can see with the last one, both mentions and pins are affected, but it appears pins more so)

(I was using the dark theme, but the problem does not appear to change with the light theme)

**Comment by Zerthox** [comment]
Thanks for pointing that out, gonna be improved with next verison.
