### ISSUE TITLE
I wanna change the font on my own.

### ISSUE THREAD

**Issue by aScHEABL** [Zerthox/ClearVision#35]
Hey bro, my native language is not english,it's chinese. my problem with this theme is the original font(default) with chinese is fuckin' ugly
i understand the usage of CSS, after seeing your code (on web) is uneasy to find out which line to change the font, so i need the original .css file
BTW if i download your .css file from the web directly, the content isn't organized. (like the pic below)
and if i download your standard .css file, it link to your web .css file
could you pls provide me your original .css file? many thx

![unknown](https://cloud.githubusercontent.com/assets/22256864/26763267/93b1b186-4982-11e7-942f-4a3133943d83.png)

**Comment by tehbasshunter** [comment]
While that is the code for the theme that's not the one you want. You want one of [**THESE**](https://github.com/Zerthox/ClearVision/tree/master/themes).  
  
I'm not sure about the font changing to another part though.

**Comment by Zerthox** [comment]
What you grabbed is the minified version of the CSS, which is loaded by the theme.  The human readable version of the CSS can be found [here](https://github.com/Zerthox/ClearVision/blob/master/css/ClearVision_v5.css).

However, ClearVision does not change the font in any way and thus there is nothing regarding the font in the ClearVision source code. You'll have to change the font yourself.

You can either do it the old fashioned way and simply use the local font name (Depending on the font there might be issues with that though) or use font-face. Info about font-face:  [@Font-face on MDN](https://developer.mozilla.org/de/docs/Web/CSS/@font-face), [@Font-face on CSS-Tricks](https://css-tricks.com/snippets/css/using-font-face)

**Comment by aScHEABL** [comment]
@font-face {
  font-family: 'Noto Sans TC';
  font-style: normal;
  font-weight: 100;
  src: url(//fonts.gstatic.com/ea/notosanstc/v1/NotoSansTC-Thin.woff2) format('woff2'),
       url(//fonts.gstatic.com/ea/notosanstc/v1/NotoSansTC-Thin.woff) format('woff'),
       url(//fonts.gstatic.com/ea/notosanstc/v1/NotoSansTC-Thin.otf) format('opentype');
}

after i typed in betterdiscord custom css it doesnt work.... hmm
is that correct?

**Comment by Zerthox** [comment]
Try removing the `font-style: normal;` and `font-weight: 100;`. You wanna define your font globally, not only for text with those specific style rules.

**Comment by aScHEABL** [comment]
![image](https://user-images.githubusercontent.com/22256864/27007143-3b3a5596-4e7b-11e7-9e23-cdd9f3e8d414.png)
![image](https://user-images.githubusercontent.com/22256864/27007218-800f4e68-4e7d-11e7-8966-ed785dcb1e63.png)
![image](https://user-images.githubusercontent.com/22256864/27007222-8b227b2c-4e7d-11e7-96c6-789fb1bff21d.png)
Noto Sans TC should be looks like this

![image](https://user-images.githubusercontent.com/22256864/27008396-5de95688-4ea2-11e7-9078-d418f3505cee.png)

apparently, it doesn't  work, is there anything i miss?
@Zerthox 
anyways, i really appreciate your help, though it isn't an issue with this theme.
thus, is there any plan to add other font styles into your theme? 'cause DarkMatter did that
i mean, i'm not the only one who wanna change default font, there are many other users all over the world.

**Comment by DOBss** [comment]
try this ;)
```
a, abbr, acronym, address, applet, big, blockquote, body, caption, cite, code, dd, del, dfn, div, dl, dt, em, fieldset, form, h1, h2, h3, h4, h5, h6, html, iframe, img, ins, kbd, label, legend, li, object, ol, p, pre, q, s, samp, small, span, strike, strong, sub, sup, table, tbody, td, tfoot, th, thead, tr, tt, ul, var {
font-family: 'Noto Sans TC';
}
@font-face {
font-family: 'Noto Sans TC';
font-style: normal;
font-weight: 100;
src: url(//fonts.gstatic.com/ea/notosanstc/v1/NotoSansTC-Thin.woff2) format('woff2'),
url(//fonts.gstatic.com/ea/notosanstc/v1/NotoSansTC-Thin.woff) format('woff'),
url(//fonts.gstatic.com/ea/notosanstc/v1/NotoSansTC-Thin.otf) format('opentype');
}
```
