### ISSUE TITLE
Portion of theme not working

### ISSUE THREAD

**Issue by DominicaRand** [Zerthox/ClearVision#36]
![error](https://user-images.githubusercontent.com/29266914/26908775-79485142-4c2f-11e7-9fb2-79c00d1ad695.PNG)

Theme: Clear Vision Sapphire 

The channel bar is not showing up properly.

**Comment by ghost** [comment]
I too have this problem using the Ruby theme.
![untitled](https://user-images.githubusercontent.com/29267348/26909438-cc818af6-4bce-11e7-915e-af69e7c47344.png)

**Comment by nekoma0** [comment]
maybe discord have some update that broke the theme, wait zerthox to update it.
i have the issue as well.

**Comment by tehbasshunter** [comment]
Until he fixes it use this for now https://github.com/GimoTheBeast/Discord-Theme-Fixes

**Comment by DominicaRand** [comment]
no fix yet

**Comment by Zerthox** [comment]
Fixed with 5.2.3
