### ISSUE TITLE
Mute icon shows deafen icon instead when only muted is selected

### ISSUE THREAD

**Issue by iGeMiNix** [Zerthox/ClearVision#38]
Hello Zerthox. I am pretty new to discord themes and github so please correct me of this is not the right way to report these issues. So this only happens when anybody is just muted. It will show the deafen icon instead of the muted. However, when deafen and muted are both selected, both icons appear so it is fine. I am guessing it might have to do with the order of the icons on how they appear. It also appears in all version of the skin and easily replicable. Thanks for the skin.

Edit: Fixed in the most recent update. Can be closed now.

**Comment by DetermineAbsurd** [comment]
Kind of redundant, but here is an image to show clarity.
![discord_2017-06-11_12-15-59](https://user-images.githubusercontent.com/12719642/27012574-147f6340-4ea0-11e7-8ce4-61dda592d272.png)

This only shows in the voice channel, not the button.
