### ISSUE TITLE
Unread channels don't show a dot next to them anymore, only light up

### ISSUE THREAD

**Issue by CreatorKami** [Zerthox/ClearVision#39]
Starting up Discord today, the unread channels don't have a notification dot anymore, only a light. The font is also bigger I think? Here is an image comparing an unread channel (top) vs one with no new messages (bottom)
![image](https://user-images.githubusercontent.com/21697910/27042787-021793f0-4f66-11e7-8ae3-6c6e0729e3c1.png)

**Comment by Zerthox** [comment]
That is intended.

**Comment by CreatorKami** [comment]
Is there any way to disable this? The new message light is very difficult to see.

**Comment by Zerthox** [comment]
You can display the little dot again, but it's not styled. I will probably adress this and make a more visible marker for unread channels in a future update.

**Comment by CreatorKami** [comment]
It's fine if it isn't styled! May I ask how to display it?

**Comment by Zerthox** [comment]
```css
.channels-wrap .scroller [class*="unread"] {
    display: initial !important;
}
```

**Comment by CreatorKami** [comment]
Thank you very much! I look forward to a future update in which the marker is more visible! :)
