### ISSUE TITLE
Weird problem with voice/text channels and scrolling

### ISSUE THREAD

**Issue by popcorn9499** [Zerthox/ClearVision#4]
Im running discord canary on linux with better discord and when i have the window smaller so i have to scroll the channels move around constantly This is a [link](https://images.discordapp.net/.eJwNx0EOgyAQAMC_cIeFFVzwFf7AEKRIqsXA9tT07-3c5iPe_RSLOJjvsQDsdaTWdzW49ViyKq2VM8e7DpXaBZE5puPKLx6AU0AyqK3TNoSJAgLOMxH9a6z13qH1sOb83FAbktpI7TY00jlV6kN8f-jbJPY.aWhjZP0uj-NwssLqDh2nRvx0dYg) To what im talking about

**Comment by Zerthox** [comment]
Only happening when the theme is applied?

**Comment by popcorn9499** [comment]
Yes it did because I removed it and no more problems occurred.

**Comment by Drakonas** [comment]
I'm having this issue as well. it only occurs once the voice list is scrolled down. if the list is scrolled all the way to the top, then there is no issue. EDIT: It also doesn't happen if nobody is in the voice channels. I think I had this issue once and I found it was that the avatars for each user were being temporarily resized/updated every time you hover over a channel. Or at least something to that extent.

**Comment by Zerthox** [comment]
@Drakonas thanks for the additional information, now i can check out if i can reproduce it and how i can fix it

**Comment by Zerthox** [comment]
Fixed it, the negative z-index on the pseudo element caused the flicker
