### ISSUE TITLE
Community maintenance?

### ISSUE THREAD

**Issue by Hebgbs** [Zerthox/ClearVision#48]
Since you're not awfully motivated to do some work on it, how about making a new sheet for us to edit and chain-import via the base import until you don't feel so burned out? I've been talking with people about this in the Discord server.

People who gave money to the project can finalize RC's of additional base code from free users and you can finalize candidates for inclusion. That would mean less coding for you, and a better theme for all if we can use GitHub for what it was meant; _social coding._

**Comment by OmgDani** [comment]
sounds good, we need clear vision to be updated, its the collection of themes i have ever seen
