### ISSUE TITLE
Incompat with Canary Desktop v0.0.167

### ISSUE THREAD

**Issue by 4g0tt3nSou1** [Zerthox/ClearVision#55]
Video and Screensharing icons are wrong.

Theme is broken, no BG, and incomplete coverage. 

Current:
http://bit.ly/2gDI3Gj

How it should look (give or take.):
http://bit.ly/2gEySVU

Note, as obvious, I did some inline editing to "Patch" the call buttons. This should be non related to the break, as I simply just replaced the url with an inline replacement

**Comment by popcorn9499** [comment]
I have gotten this issue as well and im running just regular discord
