### ISSUE TITLE
Background not transparent/appearing

### ISSUE THREAD

**Issue by Shakybird** [Zerthox/ClearVision#56]
Background transparency not working as intended, and I am unable to see my custom background.
![image](https://user-images.githubusercontent.com/21094588/32084851-4ff8168a-ba91-11e7-8172-c61fb0af4582.png)
![image](https://user-images.githubusercontent.com/21094588/32084870-5e12e1f0-ba91-11e7-8858-b3909abe6885.png)
However, when I am in a menu, you can see it.

**Comment by Valiance-X** [comment]
I'm having the same issue, can't seem to figure out how to fix it.

**Comment by Endlesszombiez** [comment]
Until Zerthox uploads a fixed version there is a slight workaround.

Go to custom CSS, paste this in there:
.container-2OU7Cz, .theme-dark .title-qAcLxz, .channels-3g2vYe, .theme-dark .chat form, .theme-dark .headerBar-cxbhPD {
    background-color: transparent;
}

css.theme-dark .title-qAcLxz, .channels-3g2vYe {
Background-color: transparent !important;
}

.titleWrapper-3Vi_wz {
    Background-color: rgba(0, 0, 0, 0.8) !important;
}

/* Main background and settings background */
.app,
.callout-backdrop {
    background-size: cover !important;
}

.container-2OU7Cz, .channels-3g2vYe, .title-qAcLxz,
.theme-dark .chat form, .headerBar-cxbhPD
{ background-color: transparent; }

/* Channel List, Server Name */
.channels-3g2vYe, .title-qAcLxz {
    background-color: rgba(0, 0, 0, 0.7) !important;
}

/* Channel Name Bar */
.theme-dark .title-qAcLxz {
    background: rgba(0, 0, 0, 0.8) !important;
}

/* Friends Header */
.headerBar-cxbhPD {
    background-color: rgba(0, 0, 0, 0.9) !important;

 }

Hit update hit save a couple times then type Ctrl + R.

If for some reason the CSS doesnt save across exiting discord/rebooting etc. You can paste the code at the bottom of the Theme file.

**Comment by Zerthox** [comment]
Fixed by now
