### ISSUE TITLE
background image

### ISSUE THREAD

**Issue by SkyfrostN7** [Zerthox/ClearVision#57]
Hello Zerthox!
I really like your theme Clear Vision Sapphire.
But please delete from the background is the name: Stellar Collision Kuldar Leement.
It is mixed with the button closing the Discord window
Looks like this : http://radikal.ru/fp/8zjgp6vv6imu5 
Thank you in advance

**Comment by HorizonCode** [comment]
Until Zerthox uploads a fixed version there is a little workaround for your issue.
add this into your custom css

[class*="titleBar-"]{
    background-image: linear-gradient(#202225, #202225) !Important;
    margin-top: 0px !Important;
    padding-top: 4px !Important;
}

**Comment by SkyfrostN7** [comment]
Thank you for a temporary solution

**Comment by Zerthox** [comment]
Sorry, but I won't delete that. It's part of the image and if the creator decided he wanted to leave it there, I won't take an effort and photoshop it away.

**Comment by SkyfrostN7** [comment]
Thanks for the help, I will have to use other themes.
На 24.11.2017 21:13:48, Zerthox <notifications@github.com> писал:
Sorry, but I won't delete that. It's part of the image and if the creator decided he wanted to leave it there, I won't take an effort and photoshop it away.
