### ISSUE TITLE
LFG does not show properly

### ISSUE THREAD

**Issue by animeboi** [Zerthox/ClearVision#68]
Everything else looks right except for this screen:
![image](https://user-images.githubusercontent.com/30117600/34465072-c0dea23e-ee6b-11e7-8f38-68649a663486.png)

I fixed it with this:
![image](https://user-images.githubusercontent.com/30117600/34465079-e9f54a60-ee6b-11e7-8840-b49aea76ae52.png)

**Comment by Zerthox** [comment]
The LFG panel is pretty new and not available for everyone yet, thus it isn't styled yet.

**Comment by animeboi** [comment]
Is there a way I can make it so that I don't have to make that modification every time I restart Discord?
