### ISSUE TITLE
Support for CSS linear gradients

### ISSUE THREAD

**Issue by Cyxo** [Zerthox/ClearVision#69]
Hello,

When I set the `--main-color:` to a CSS linear-gradient (like `linear-gradient(135deg, #fb575d 0%,#7db9e8 100%)` ) in Custom CSS, it only works for several things like the background of the private messages icon, the little dot next to the servers' icon or the slider bars,but it doesn't work for the color of the selected channel, the border of the message text box, or even not for the background of the buttons at the bottom of the Custom CSS page.

Could you do so it fully supports linear-gradients ? Because it can be so aesthetic !

(Btw here are a few CSS tricks to put gradients to :
- Text : https://css-tricks.com/snippets/css/gradient-text/
- Borders : https://css-tricks.com/examples/GradientBorder/ )

**Comment by Zerthox** [comment]
Gradients are treated as images in CSS. And since the main color is supposed to be a color, not an image, it will not work everywhere.

You or somebody else can work on a mod fixing the issues with gradients if you want to. But I won't do it.
