### ISSUE TITLE
Context menu and some transparency problems

### ISSUE THREAD

**Issue by br4k4g3** [Zerthox/ClearVision#72]
Since few hours ago, right click context menu has a default discord colors/transparency also "xxxx is typing" has a weird grey box all around it and element where channels and servers are listed is very bright all of the sudden even if i put background brightness low.

**Comment by OmgDani** [comment]
i'll work on it

**Comment by br4k4g3** [comment]
Thanks for the quick response! Seems like right click context window(has a default dark mode colors) and server context window(has a light mode colors) are still broken (not sure if you started working on that yet) Just wanted to give an update.

**Comment by OmgDani** [comment]
should all be fixed now

**Comment by br4k4g3** [comment]
Everything seems to be back to normal! Thanks for fixing the stuff.
