### ISSUE TITLE
Uhhh theme is bright as hell 

### ISSUE THREAD

**Issue by DerKen16** [Zerthox/ClearVision#74]
Idk what happened I logged in and I got this ._. it's giving me cancer tbh lmao help
![image](https://user-images.githubusercontent.com/19639815/35025327-6f887fbc-fb0a-11e7-9f2b-581c4352ca49.png)

**Comment by OmgDani** [comment]
Should be fixed

**Comment by DerKen16** [comment]
oooo it's fixed now thanks :D
