### ISSUE TITLE
During DM calls I get this 

### ISSUE THREAD

**Issue by DerKen16** [Zerthox/ClearVision#76]
help lul
![image](https://user-images.githubusercontent.com/19639815/35095180-29b3cb00-fc0d-11e7-877b-2adee3add9c1.png)

**Comment by OmgDani** [comment]
i thought i fixed that

**Comment by DerKen16** [comment]
Also while sending files too 
![image](https://user-images.githubusercontent.com/19639815/35096395-a3b0c4fe-fc11-11e7-9bb4-3e8435182ef5.png)

**Comment by OmgDani** [comment]
i fixed both of these issues yesterday
