### ISSUE TITLE
is it the way it should be?

### ISSUE THREAD

**Issue by ghost** [Zerthox/ClearVision#79]
![screenshot_4](https://user-images.githubusercontent.com/29844383/36307120-a443ae14-132b-11e8-836c-6fe8688a1090.png)

**Comment by OmgDani** [comment]
no it shouldn't be like that i'll fix it

**Comment by ghost** [comment]
perhaps this is due to a recent update

**Comment by ghost** [comment]
and when i am click on the user, he does not have background, just transparent

**Comment by OmgDani** [comment]
to fix that change 
.user-popout::before,

 to
[class*=userPopout-]::before,

in your theme file. (This should be line 41.)

**Comment by ghost** [comment]
thanks
