### ISSUE TITLE
Some of the things have the default discord look

### ISSUE THREAD

**Issue by Taffey813** [Zerthox/ClearVision#86]
So after discord updated some of the things stayed default even with the theme on.

![image](https://user-images.githubusercontent.com/29903976/39409867-2eb6bcc6-4bbc-11e8-8788-cea26b19b6b3.png)
![image](https://user-images.githubusercontent.com/29903976/39409871-3861419c-4bbc-11e8-9d67-bd75bac00b6c.png)
![image](https://user-images.githubusercontent.com/29903976/39409907-8bf561bc-4bbc-11e8-87f8-566fbd926f99.png)
![image](https://user-images.githubusercontent.com/29903976/39409878-4e95e332-4bbc-11e8-9ba7-8695427036f9.png)
![image](https://user-images.githubusercontent.com/29903976/39409891-62b27af6-4bbc-11e8-8c7f-88fda6442b5f.png)

There is maybe more but these are the things that I noticed.

**Comment by OmgDani** [comment]
Fixed!
