### ISSUE TITLE
Screen sharing icons aren't changed

### ISSUE THREAD

**Issue by Taffey813** [Zerthox/ClearVision#88]
![unknown 4](https://user-images.githubusercontent.com/29903976/39656763-48619b10-4fd0-11e8-86c4-db22bf5ef014.png)
(The microphone is the screenshare button and the gear is the video cam button)
Also the fullscreen icon on screenshare shows as a gear (not the one in the picture)

**Comment by OmgDani** [comment]
This has been fixed for a while now i think
