### ISSUE TITLE
Settings background not transparent

### ISSUE THREAD

**Issue by maam27** [Zerthox/ClearVision#90]
After the most recent discord update (the one that required a reinstall of better discord bandaged) the background of the settings panel is no longer transparent. This appears in the settings as well as server settings.

I solved this issue by adding a new theme that added the following css lines as a quick fix.

```
.contentRegionScroller-26nc1e,
.theme-dark .da-sidebarRegion,
.theme-dark .da-contentRegion,
.theme-dark .da-standardSidebarView,
.theme-light .da-sidebarRegion,
.theme-light .da-contentRegion,
.theme-light .da-standardSidebarView{
    background-color:transparent;
}
```

**Comment by AutumnClove** [comment]
Redundant, having two classes when we can just [class*="theme-"]

**Comment by Yohji52** [comment]
Works, thanks!

**Comment by noblereign** [comment]
Thanks 👌

**Comment by noblereign** [comment]
Thanks 👌

**Comment by AztralMenu** [comment]
did not work :l
