### ISSUE TITLE
Theme does not apply to blocked user's messages

### ISSUE THREAD

**Issue by QuentinMcCarthy** [Zerthox/ClearVision#91]
I don't usually block people so I've only recently noticed this, but any messages from a blocked user do not have Amethyst applied to it.

![capture](https://user-images.githubusercontent.com/36647653/47406406-93493880-d7b2-11e8-860d-f6827850e8f4.PNG)

**Comment by OmgDani** [comment]
Fixed!

**Comment by QuentinMcCarthy** [comment]
Can confirm, fixed.
