### ISSUE TITLE
In Game Activity, Games Appear cut off

### ISSUE THREAD

**Issue by voxelvortex** [Zerthox/ClearVision#92]
![image](https://user-images.githubusercontent.com/20521924/49623405-92075000-f99b-11e8-8273-42601d3d6c5c.png)

As you can see the list of games appear to be cut off at the edges, this is occurring on discord canary, I'm running the latest version on windows 10. I checked to make sure this issue wasn't happening on other themes before posting.

**Comment by OmgDani** [comment]
Should be fixed now :)

**Comment by voxelvortex** [comment]
Appears to be fixed on my end too :)
