### ISSUE TITLE
Background image from local file

### ISSUE THREAD

**Issue by TrademarkTM** [Zerthox/ClearVision#93]
I'd like to know if it's possible to use a background image from a local file, instead of a https link. Is this a feature already, or will it be added at some point?

Amazing theme, btw.
Thanks!

**Comment by OmgDani** [comment]
I don't believe this is possible but there is a plugin that can allow you to do it https://github.com/Inve1951/BetterDiscordStuff/blob/master/plugins/localFileServer.plugin.js

**Comment by Zerthox** [comment]
As @OmgDani said, it is not possible unless you host the file on a local server.
