### ISSUE TITLE
Navigation Portion of theme not working(3/7/19)

### ISSUE THREAD

**Issue by TheVelvetDruid** [Zerthox/ClearVision#97]
Just had an update for Discord (3/7/19 @ 10:20PM Est.) and afterwards the side navigation for server lists is no longer stylized.
![themeissue](https://user-images.githubusercontent.com/27750853/54005651-42662b00-4128-11e9-9b72-fdb2086c806f.png)

**Comment by tropicaaal** [comment]
Discord recently updated guilds classes. I made some fixes for it, and you can apply it.
`[class*="theme-"] .wrapper-1Rf91z {
  background-color: rgba(0, 0, 0, 0.35);
}
[class*="theme-"] .guild-1EfMGQ.unread-qLkInr:before {
  background-color: var(--main-color);
}
[class*="theme-"] .homeIcon-tEMBK1:hover {
  background: var(--hover-color);
}
[class*="theme-"] .homeButton-2Cw51C[style*="background-color"] {
    background:var(--main-color) !important;
}
[class*="theme-"] .homeButton-2Cw51C[style*="47, 49, 54"] {
    background-color:var(--main-color) !important;
}
[class*="theme-"] .container-2td-dC.selected-nT-gM3:before {
  background: var(--main-color) !important;
  animation: selectserver .5s cubic-bezier(0.22, 0.61, 0.36, 1);
  -webkit-animation: selectserver .5s cubic-bezier(0.22, 0.61, 0.36, 1);
}
[class*="theme-"] .circleIconButton-jET_ig {
  background: rgba(0, 0, 0, 0.5);
  border-color: var(--main-color);
  color: var(--main-color);
}
[class*="theme-"] .circleIconButton-jET_ig:hover {
  border-color: var(--hover-color);
  color: var(--hover-color);
}
[class*="theme-"] .wrapper-2lTRaf {
  background: rgba(0, 0, 0, 0.5) !important;
}
[class*="theme-"] .friendsOnline-2JkivW {
  background: rgba(21, 21, 21, 0.41);
  border-radius: 25px;
  color: #DCDCDC;
  text-transform: uppercase;
  -webkit-transition: all .3s ease-in-out;
  transition: all .3s ease-in-out;
  overflow: hidden;
  cursor: default;
}` or you can wait until danielle fixes it.

**Comment by TheVelvetDruid** [comment]
Sounds good either way.

**Comment by OmgDani** [comment]
This has been fixed for everyone using clearvision now.
