### ISSUE TITLE
The New Discord Update Broke All Of The Clear Vision Themes!

### ISSUE THREAD

**Issue by Benzeel** [Zerthox/ClearVision#98]
So Devilbro Said The New DIscord Update Changed A lot of classes Or Something And It Kinda Broke The Theme Too

**Comment by Shadowsoftime99** [comment]
Seconding this, a lot of previously colored areas are overwritten by the new gray elements and accents that Discord and thus Base BD added.

**Comment by Zerthox** [comment]
@OmgDani feel free to close this when you feel like the majority is fixed.
